### ISSUE TITLE
project status and other questions

### ISSUE THREAD

**Issue by jjpepper** [gmggroup/omf-python#28]
Hi everyone... anyone...

How alive is this repo? Is anyone actively involved in doing work on it in a funded and sustainable capacity?  I have a few questions about the foundations of this push.  One of my initial questions is are there any descriptions of the formats described here outside of the python code?  Python is not an ideal medium to express a format in my opinion since it's a weakly typed language.  Is the idea to define a compact binary format akin to google protobuf for efficient storage and transmission of these data types, or is the idea to provide something human readable (or both)?

**Comment by banesullivan** [comment]
Hi @jjpepper, I am in no way affiliated with @GMSG-DataExchange or the `omf` project but I think I can answer a few of your questions/concerns.

> Are there any descriptions of the formats described here outside of the python code?

The Open Mining Format Specification is generally described [here](
https://gmggroup.org/projects/data-exchange-for-mine-software/). As for learning the data format, the [code docs](https://omf.readthedocs.io/en/latest/index.html) for this repo have been especially helpful for me.

> Python is not an ideal medium to express a format in my opinion since it's a weakly typed language.

Python’s weak/dynamic typing can definitely be problematic which is why `omf` Is built upon [`properties`](https://github.com/seequent/properties) (actively maintained) for the creation of strongly typed objects. Also, the Open Mining Format is not exclusive to Python. It’s simply a serialized data format that makes sense when using standard array/vector data types in your language of choice.

> Is the idea to define a compact binary format akin to google protobuf for efficient storage and transmission of these data types, or is the idea to provide something human readable (or both)?

I am not familiar with protobuf and again I am not affiliated with this project, but I think the goal is to provide a simple, easy to use serialized (binary) data format for efficient storage, retrieval, and transmission of data.

Overall I am a huge fan of this idea, having a simple serialized data format with an intuitive interface in Python (or Java, C#, etc.), however I don’t think anyone is really pushing these standards or promoting the adoption of them besides Seequent’s leapfrog being compatible with `omf`.

**Comment by rowanc1** [comment]
Thanks @banesullivan! There are a few companies other than Seequent that have picked up OMF v1, including Deswik; some others will also announce soon. A talk from a few months ago is here:

https://external.opengeospatial.org/twiki_public/pub/GeoScienceDWG/WebHome/5-2018_Orleans_GMSG_Andrew_Scott.pdf

![image](https://user-images.githubusercontent.com/913249/47491831-244e0b80-d8a8-11e8-863a-efc718aaf245.png)

I think that the take-aways from that talk are also worth highlighting here:

* We have focused on the foundation, not objects
* It demonstrates that a solution is possible and actually not that hard
* V1.0 is as much about *changing mindsets* as it is about a technical solution

Next Steps include:
* We need to explore development of V2.0 and/or adoption of other standards
* We need to get permanent management of this solution (Technical, project management).

----

The goal of OMF v1 is to prove out the ideas and drive some adoption throughout the industry, it is slowly gaining some traction, and next steps will be to explore or incorporate other standards (such as protobuf). That work would probably also add other client libraries around the reference implementation that this python library provides. The goal of the first version is mostly (in my opinion) to prove out the acronym (open mining format) rather than all of the technology behind it. Lots more to do in thinking forward to the next version!

I hope that helps give some more pointers and information, there should also be some links on the GMG website to join the working group if you are inclined!

**Comment by rowanc1** [comment]
Quick update, Geovia just released OMF v1 support:

https://www.3ds.com/fileadmin/PRODUCTS-SERVICES/GEOVIA/PDF/datasheet/GEOVIA-Surpac2019-WhatsNew.pdf

![image](https://user-images.githubusercontent.com/913249/49383882-0493d980-f6d7-11e8-8678-40e129762726.png)
